name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kolezka
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Warsaw
          config_output: svg

          # Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Stars
          plugin_stars: yes
          plugin_stars_limit: 4
